Fixed React warning about document.body as a container in the tests
ERROR: 'Warning: render(): Rendering components directly into
document.body is discouraged, since its children are often manipulated
by third-party scripts and browser extensions. This may lead to subtle
reconciliation issues. Try rendering into a container element created
for your app.'